spring.application.name=SmartHealthChain

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/smart_health_chain
spring.datasource.username=root
spring.datasource.password=Sushant123#17

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

