spring.datasource.url=jdbc:mariadb://localhost:3306/SmartHealthChain
spring.datasource.username=root
spring.datasource.password=Sushant123#17
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.data.jdbc.repositories.enabled=true
logging.level.org.springframework=INFO
logging.level.com.smarthealthchain=DEBUG